In [1]:
import pickle
import CTMParallel
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression



Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode EXPIRED 4 days ago

    Your usage of mkl is now out of compliance with the license agreement.
    A license for mkl can be purchased at: http://continuum.io
    


In [2]:
# Returns the min, max, and average accuracy across the folds
def KFoldCrossValidation(X, Y, num_folds, print_outputs=True):
    accuracies = []
    for train, test in KFold(X.shape[0], num_folds, shuffle=True):
        X_train, X_test, Y_train, Y_test = X[train], X[test], Y[train], Y[test]
        logistic_classifier = LogisticRegression()
        logistic_classifier.fit(X_train, Y_train)
        accuracies.append(accuracy_score(logistic_classifier.predict(X_test), Y_test))
    if print_outputs:
        print "Max Accuracy: ", max(accuracies), "\nMin Accuracy: ", min(accuracies), "\nAverage Accuracy: ", sum(accuracies)/len(accuracies)
    return max(accuracies), min(accuracies), sum(accuracies)/len(accuracies)

In [2]:
model = pickle.load(open("pickled_objects/model2all.p", "rb"))

In [47]:
classes = pickle.load(open("pickled_objects/ytrain2.p", "rb")).astype(int)
vocab = pickle.load(open("pickled_objects/vocab2.p", "rb"))

In [21]:
np.sum(model.saved_lambdas, axis=0)/500

array([-0.03702926, -0.03913617, -0.00278356,  0.01772189, -0.01369278,
       -0.00544263,  0.02782353,  0.00454954, -0.00705286,  0.01849104])

In [4]:
train = model.saved_lambdas[:400]
test = model.saved_lambdas[400:]
ytrain = classes[:400]
ytest = classes[400:]

In [28]:
clf_new = SVC()
clf_new.fit(train, ytrain)
#accuracy = accuracy_score(clf_new.predict(test), ytest)
print clf_new.predict(test)
accuracy_score(clf_new.predict(test), ytest)

[3 4 3 3 3 3 3 3 4 3 3 4 3 3 3 3 4 3 4 4 3 4 3 4 3 3 3 4 3 3 4 3 4 3 4 3 3
 4 4 3 3 3 3 4 4 3 3 4 3 3 3 4 3 4 3 3 4 3 4 4 3 3 3 3 3 3 3 3 3 4 3 4 3 4
 3 3 3 4 3 3 3 4 3 3 3 3 4 4 3 3 3 4 3 3 3 4 4 3 4 4]


0.55000000000000004

In [46]:
model.beta

array([[  1.83980724e-03,   1.54193511e-03,   2.72812643e-03, ...,
          5.87663877e-06,   6.98193337e-07,   1.03825588e-06],
       [  1.55751903e-03,   3.45780897e-04,   1.76039664e-04, ...,
          2.80629787e-06,   1.37861005e-06,   5.47598621e-07],
       [  1.23266718e-03,   2.34966054e-03,   1.07062053e-03, ...,
          2.08968662e-07,   4.49007654e-07,   1.80547039e-06],
       ..., 
       [  1.89113328e-03,   2.19160621e-03,   3.38549396e-03, ...,
          3.85065800e-06,   2.63806369e-06,   1.90606428e-06],
       [  2.61815433e-03,   1.02113262e-03,   1.88087681e-03, ...,
          4.20443035e-06,   3.55334237e-06,   6.26208429e-06],
       [  2.49772898e-03,   3.42468308e-03,   2.18003876e-03, ...,
          4.26086897e-06,   5.71613178e-06,   1.11735142e-06]])

In [58]:
n_top_words = 20
for i, topic_dist in enumerate(model.beta):
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-n_top_words:-1]
    print('Topic {}: {}'.format(i+1, ' '.join(topic_words)))

Topic 1: Snhg11 Sub1 Ppp3ca Ddx5 Cpe Slc25a4 Map1b Syt1 Syt11 Serinc1 Rtn1 Itm2b Hspa8 Ndufa4 Snca Ttc3 Kif1b Gstp1 Ywhag
Topic 2: Scg5 Nrgn Aldoa Tubb2a Chn1 Stmn3 Itm2b Prnp Rtn1 Ppp3ca Slc25a4 Calm3 Cpe Fkbp1a Snhg11 Tcf4 Mdh1 Cox7c Aplp1
Topic 3: Snhg11 Hspa8 Syt11 Scg5 Rtn1 Lars2 Rps29 Mdh1 Slc25a4 Ttc3 Stmn3 Cst3 Dynll1 Cox7c Prnp Atp6v1a Hpca Ndufa4 Mog
Topic 4: Cst3 Gstp1 Ndufa4 Serinc1 Syt1 Mdh1 Aplp1 Rtn1 Ddx5 Ttc3 Cpe Atp6v1a Cox8a Itm2b Stmn3 Rps29 Hpca Dynll1 Sst
Topic 5: Ttr Aldoa Prkcb Syt1 Rps29 Map1b Atp6v0c-ps2 Actg1 Npy Atp5a1 Snca Ckb Cpe Sparcl1 Gpm6b Sub1 Itm2b Atp5g3 Chn1
Topic 6: Ndufa4 Snhg11 Npy Atp6v1a Map1b Actg1 Ywhaz Slc25a4 Ttc3 Cpe Ptgds Tpi1 Syt1 Sub1 Nrgn Scd2 Snurf Cycs Gm5506_loc1
Topic 7: Ptgds Rps29 Apod Mbp Cst3 Mdh1 Enpp2 Cd81 Stmn3 Car2 Lars2 Slc25a4 Fkbp1a Rtn1 Tcf4 Syt11 Aldoa Actg1 Ptma
Topic 8: Mdh1 Syt1 Snca 2900097C17Rik Lars2 Syt11 Gstp1 Atp6v0c-ps2 Dynll1 Rps29 Ndufa4 Apod Scd2 Chn1 Serinc1 Scg5 Cst3 Calm3 Atp5b
Topic 9: Prkcb Ppp3ca Ald

In [57]:
model.sigma

array([[  6.70421300e-01,   1.72161600e-02,   2.49712578e-03,
         -7.84727266e-03,   4.47817979e-03,   9.99664942e-04,
         -1.50568785e-02,  -2.51553479e-03,   8.82178073e-04,
         -8.30578223e-03],
       [  1.72161600e-02,   6.73010341e-01,   2.75443500e-03,
         -9.43203810e-03,   4.36411319e-03,   2.21710892e-03,
         -1.55654098e-02,  -1.87742585e-03,   1.55915486e-03,
         -9.42240774e-03],
       [  2.49712578e-03,   2.75443500e-03,   6.54195927e-01,
         -8.01985300e-04,   9.38145201e-04,   2.68442707e-05,
         -2.75954319e-03,  -2.63659721e-04,  -6.31642978e-04,
         -1.00907940e-03],
       [ -7.84727266e-03,  -9.43203810e-03,  -8.01985300e-04,
          6.58304398e-01,  -1.59756614e-03,  -1.67591357e-03,
          6.76596246e-03,   9.23432330e-04,  -1.52662905e-03,
          5.00254034e-03],
       [  4.47817979e-03,   4.36411319e-03,   9.38145201e-04,
         -1.59756614e-03,   6.55571795e-01,   3.81310093e-04,
         -4.79687311e-03

# Rat Dataset, 10 topics

In [3]:
import pickle
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.decomposition import PCA
from sklearn.cross_validation import KFold


### Load Model

In [72]:
# Load the trained model
model_rat_10topics = pickle.load(open("pickled_objects/modelratserial.p", "rb"))
classes_rat_10topics = pickle.load(open("pickled_objects/classesratserial.p", "rb"))
vocab_rat_10topics = pickle.load(open("pickled_objects/vocabratserial.p", "rb"))
counts_rat_10topics = pickle.load(open("pickled_objects/countsratserial.p", "rb"))


(1.0, 0.96875, 0.97812500000000002)

### Determine classification accuracy on CTM features

In [87]:
max_acc, min_acc, avg_acc = KFoldCrossValidation(model_rat_10topics.saved_lambdas, classes, 5)

Max Accuracy:  0.984375 
Min Accuracy:  0.953125 
Average Accuracy:  0.975


### Get the top genes in each topic

In [118]:
# Get the top genes in each topic
n_top_words = 20
for i, topic_dist in enumerate(model_rat_10topics.beta):
    topic_words = np.array(vocab_rat_10topics)[np.argsort(topic_dist)][:-n_top_words:-1]
    print('Topic {}: {}'.format(i+1, ' '.join(topic_words)))

Topic 1: stonee gokla stawflu Spnb2 Col3a1 Mb Eef1a1.1 Atp5a1 Dst Hbb Myh9 Sparc Hba-a2 Ccdc107 Sftpc B2m Ryr2 Gsn Actb
Topic 2: Alb Trf Cps1 Apob Ahsg Kng1andKng2 Apoe Rspo3 Rbp4 Rmrp Ttr Gc Cfh Serpinc1 Cyp2e1 Mug1 Itih3 Scd1 Eef1a1.1
Topic 3: gokla stonee Eef1a1.1 Eef1a1 Aldob Lyz2 gawkla Rmrp Sepp1 Sftpc Ctsl Eef2 C4aandC4-2 Atp1a1 Pck1 Ubc Ctsb Apoe Aldh6a1
Topic 4: Hbb stonee Hba-a2 Rmrp Ccdc107 LOC360504 Eef1a1.1 Eef1a1 MGC72973 Actb gokla Eef2 Amy2 Psap stawflu Ptprc B2m LOC678701 Rpl4
Topic 5: gokla stawflu Rmrp stonee Hsd3b1 Ccdc107 Eef1a1.1 Scd1 Eef1a1 Hao2 Plp1 Cyp11a1 Cyp21a1 Umod Spna2 Cyp11b1 Atp5b Dst Syne1
Topic 6: Myh6 Atp2a2 Myh7 Atp5b Ryr2 stonee Hbb Actc1 Tnnt2 stawflu gokla Rmrp Myl2 Col3a1 Tnni3 Mybpc3 Myl3 Lpl Atp5a1
Topic 7: Myh4 Acta1 Ckm Tpm1 Pkinase.4 snoflu Ttn Tnnt3 Myl1 Myosin_tail_1.1 Actn3 Aldoa Mb Tnni2 Pygm Eno3 fn3.21 I-set.16 I-set.17
Topic 8: gokla Hsd3b1 Star stonee Cyp11a1 Col3a1 Atp5b gawkla Aco2 Col1a2 Syne1 Sparc Atp1a2andAtp1a4 Abcc5 nyto Spn

In [77]:
# Print the covariance matrix between topics
model_rat_10topics.sigma

array([[ 1.95097003, -1.0838962 ,  0.74885781,  1.11017983,  1.07833787,
         1.47515872,  0.69552146,  1.06558292, -1.49773156,  1.06654061],
       [-1.0838962 ,  3.81782433,  0.51714093, -0.79596376, -0.18995724,
        -1.57807808, -2.23056967, -0.96812839,  3.72590127, -0.81540821],
       [ 0.74885781,  0.51714093,  2.27218235,  1.03908524,  1.47909758,
         0.24971437, -1.57109743,  0.44130517,  0.51706189,  0.96670897],
       [ 1.11017983, -0.79596376,  1.03908524,  3.34037111,  1.1510328 ,
         0.74777914, -1.20853617,  0.35554637, -1.18931525,  1.4001093 ],
       [ 1.07833787, -0.18995724,  1.47909758,  1.1510328 ,  3.22892075,
         0.52085326, -1.33017356,  1.43138838, -0.26380363,  1.92259898],
       [ 1.47515872, -1.57807808,  0.24971437,  0.74777914,  0.52085326,
         2.62771544,  1.77817785,  1.08844762, -2.07627106,  0.74226708],
       [ 0.69552146, -2.23056967, -1.57109743, -1.20853617, -1.33017356,
         1.77817785,  6.03194407,  0.97027417

In [31]:
# Directly use the original counts to train a LogisticRegression classifier
# Split into test and training sets for the original counts
#train_x, test_x, train_y, test_y = train_test_split(counts, classes, test_size=.2)

### Determine the classification accuracy on the original gene counts

In [90]:
#rat_original_counts_logistic = LogisticRegression()
#rat_original_counts_logistic.fit(train_x, train_y)
#accuracy_score(rat_original_counts_logistic.predict(test_x), test_y)
# Directly use the original counts to determine the cross-validation accuracy


In [93]:
min_acc, max_acc, avg_acc = KFoldCrossValidation(counts, classes, 5)

Max Accuracy:  1.0 
Min Accuracy:  0.984375 
Average Accuracy:  0.996875


### Determine the classification accuracy on the LDA-based dimensionality reduction

To do this using LDA, see the other iPython notebook, LDA.ipynb. From there, I found that the accuracy, using the same method, was .875. In other words, this method beats LDA in terms of dimensionality reduction.

### Determine the classification accuracy by applying PCA to the original counts

In [92]:
pca_rat_ctm = PCA(n_components=10)
pca_counts = pca_rat_ctm.fit_transform(counts)
min_acc, max_acc, avg_acc = KFoldCrossValidation(pca_counts, classes, 5)

Max Accuracy:  0.96875 
Min Accuracy:  0.875 
Average Accuracy:  0.915625


In [54]:
#train_x, test_x, train_y, test_y = train_test_split(pca_counts, classes, test_size=.2)

In [55]:
#rat_pca_counts_logistic = LogisticRegression()
#rat_pca_counts_logistic.fit(train_x, train_y)
#accuracy_score(rat_pca_counts_logistic.predict(test_x), test_y)

0.953125

(0.9375, 0.890625, 0.90937500000000004)

# Neuron Dataset, 10 topics

In [102]:
model_neuron_10topics = pickle.load(open("pickled_objects/model4all.p", "rb"))
classes_neuron_10topics = pickle.load(open("pickled_objects/ytrain4.p", "rb"))
vocab_neuron_10topics = pickle.load(open("pickled_objects/vocab4.p", "rb"))
counts_neuron_10topics = pickle.load(open("pickled_objects/xtrain4.p", "rb"))



### Determine classification accuracy using CTM Features

In [103]:
print "Accuracy of Logistic Regression using CTM Features"
min_acc, max_acc, avg_acc = KFoldCrossValidation(model_neuron_10topics.saved_lambdas, classes_neuron_10topics, 5)

Accuracy of Logistic Regression using CTM Features
Max Accuracy:  0.69 
Min Accuracy:  0.51 
Average Accuracy:  0.586


In [104]:
print "Accuracy of Logistic Regression using PCA Features with 10 principal components"
pca_neuron_10topics = PCA(n_components=10)
pca_features_neuron_10topics = pca_neuron_10topics.fit_transform(counts_neuron_10topics)
min_acc, max_acc, avg_acc = KFoldCrossValidation(pca_features_neuron_10topics, classes_neuron_10topics, 5)

Accuracy of Logistic Regression using PCA Features with 10 principal components
Max Accuracy:  0.94 
Min Accuracy:  0.86 
Average Accuracy:  0.898


In [106]:
print "Accuracy of Logistic Regression using original counts"
min_acc, max_acc, avg_acc = KFoldCrossValidation(counts_neuron_10topics, classes_neuron_10topics, 5)

Accuracy of Logistic Regression using original counts
Max Accuracy:  0.96 
Min Accuracy:  0.92 
Average Accuracy:  0.936


In [65]:
#train_x_neuron, test_x_neuron, train_y_neuron, test_y_neuron = train_test_split(model_neuron.saved_lambdas, classes_neuron, test_size=.2)

In [66]:
# Train LogisticRegression classifier and make predictions
# Accuracy Score is output
#neuron_ctm_logistic = LogisticRegression()
#neuron_ctm_logistic.fit(train_x_neuron, train_y_neuron)
#accuracy_score(neuron_ctm_logistic.predict(test_x_neuron), test_y_neuron)

### Get top genes in each topic

In [117]:
# Get the top genes in each topic
n_top_words = 25
for i, topic_dist in enumerate(model_neuron_10topics.beta):
    topic_words = np.array(vocab_neuron_10topics)[np.argsort(topic_dist)][:-n_top_words:-1]
    print('Topic {}: {}'.format(i+1, ' '.join(topic_words)))
    print ""

Topic 1: Slc25a4 Npy Dynll1 Snca Itm2b Rps29 Gstp1 Prnp Sub1 Syt1 Prkcb Tubb2a Hspa8 Hpca Syt11 Actg1 Atp5j2 Ywhaq Cox8a Camk2b Rplp1 Eef1a1 Gnas Stmn2

Topic 2: Ptgds Cst3 Rps29 Actg1 Lars2 Scd2 Mog Dynll1 Syt11 Car2 Usmg5 Apod Cd81 Nrgn Enpp2 Serinc1 Itm2b Arl6ip1 Qk Atp5e Ftl1 Aldoa Tubb2a Cnp

Topic 3: Rtn1 Snhg11 Ppp3ca Cpe Prkcb Serinc1 Scg5 Tubb2a Stmn3 Chn1 Tpi1 Olfm1 Nrgn Map1b Pja2 Cycs Rps29 Cox8a Eno2 Ndrg4 Calm3 Scn2a1 Atp6v1e1 Hspa8

Topic 4: Gstp1 Mbp Apod Ptma Gpm6b Mog Scd2 Cd81 Ermn Cnp Dynll1 Cst3 Aplp1 Eef1a1 Enpp2 Itm2b Ptn Rtn3 Rpl32 H3f3b Syt11 Taldo1 Atp6v1a Atp5b

Topic 5: Cpe Actg1 Slc25a4 Syt1 Mdh1 Ndufa4 Serinc1 Scg5 Ckb Sparcl1 Sub1 Prnp Tcf4 Atp6v0c-ps2 Rplp1 Atp5g3 Aldoa Slc1a2 Chn1 Usmg5 2900097C17Rik Cox7a2 Atp5j2 Ldhb

Topic 6: Snhg11 Mdh1 Sub1 Scg5 Atp6v0c-ps2 Ttc3 Nrgn Actg1 Aldoa Tcf4 Serinc1 Ppp3ca 2900097C17Rik Eif4a2 Basp1 Ywhaz Tpi1 Olfm1 Tubb2a Atp5b Cox8a Atp5g3 Prnp Snca

Topic 7: Ttr Enpp2 Cst3 Rtn1 Rps29 Snhg11 Syt11 Mdh1 Sub1 Cox7c Cox8a A

In [115]:
model_neuron_10topics.sigma

array([[ 0.6793648 , -0.020345  ,  0.03630703, -0.02157605,  0.02073142,
         0.0333818 , -0.02719253,  0.0079505 ,  0.01641649,  0.02483679],
       [-0.020345  ,  0.71648547, -0.06431401,  0.05732057, -0.03045045,
        -0.05616994,  0.03658109, -0.00585334, -0.02133856, -0.03974921],
       [ 0.03630703, -0.06431401,  0.77156903, -0.07241253,  0.05463224,
         0.08810894, -0.06769471,  0.01858201,  0.03862574,  0.0683182 ],
       [-0.02157605,  0.05732057, -0.07241253,  0.73071155, -0.03768986,
        -0.05894758,  0.03950568, -0.00546624, -0.0230056 , -0.04379379],
       [ 0.02073142, -0.03045045,  0.05463224, -0.03768986,  0.70034074,
         0.04326739, -0.03548964,  0.01410758,  0.02109201,  0.03747016],
       [ 0.0333818 , -0.05616994,  0.08810894, -0.05894758,  0.04326739,
         0.74457972, -0.06022811,  0.0168485 ,  0.03590666,  0.05843572],
       [-0.02719253,  0.03658109, -0.06769471,  0.03950568, -0.03548964,
        -0.06022811,  0.70879195, -0.01580688

# Rat Dataset 30 topics

In [107]:
model_rat_30topics = pickle.load(open("pickled_objects/modelrat30.p", "rb"))
classes_rat_30topics = pickle.load(open("pickled_objects/classesrat30.p", "rb"))
vocab_rat_30topics = pickle.load(open("pickled_objects/vocabrat30.p", "rb"))
counts_rat_30topics = pickle.load(open("pickled_objects/countsrat30.p", "rb"))


### Determine classification accuracy on CTM features

In [108]:
min_acc, max_acc, avg_acc = KFoldCrossValidation(model_rat_30topics.saved_lambdas, classes_rat_30topics, 10)


Max Accuracy:  1.0 
Min Accuracy:  0.96875 
Average Accuracy:  0.996875


### Determine classification accuracy on PCA features

In [109]:
print "Accuracy of Logistic Regression using PCA Features with 10 principal components"
pca_rat_30topics = PCA(n_components=30)
pca_features_rat_30topics = pca_rat_30topics.fit_transform(counts_rat_30topics)
min_acc, max_acc, avg_acc = KFoldCrossValidation(pca_features_rat_30topics, classes_rat_30topics, 5)

Accuracy of Logistic Regression using PCA Features with 10 principal components
Max Accuracy:  1.0 
Min Accuracy:  0.96875 
Average Accuracy:  0.984375


###Determine accuracy on LDA Features

# Rat Data - 5, 15, 25, 35, 45 Topics

In [9]:
rat_topics_options = [5, 15, 25, 35, 45]


In [10]:
# source can be either rat or neuron
def loadSavedModel(numTopics, source):
    # Load the trained model
    model = pickle.load(open("pickled_objects/" + source + "/model_" + source + "_" + str(numTopics) + "topics.p", "rb"))
    classes = pickle.load(open("pickled_objects/" + source + "/classes_" + source + "_" + str(numTopics) + "topics.p", "rb"))
    vocab = pickle.load(open("pickled_objects/" + source + "/vocab_" + source + "_" + str(numTopics) + "topics.p", "rb"))
    counts = pickle.load(open("pickled_objects/" + source + "/counts_" + source + "_" + str(numTopics) + "topics.p", "rb"))
    return model, classes, vocab, counts



In [11]:
def getClassificationAccuracy(model,classes, vocab, counts):
    return KFoldCrossValidation(model.saved_lambdas, classes, 5)   

In [12]:
# Test for classification accuracy on the rat
print "Rat Classification accuracy on raw counts"
model, classes, vocab, counts = loadSavedModel(5, "rat")
KFoldCrossValidation(counts, classes, 5)
print
print
print

for topic in rat_topics_options:
    model, classes, vocab, counts = loadSavedModel(topic, "rat")
    print "Rat Classification with numTopics = ", topic
    print "Accuracy with original features"
    getClassificationAccuracy(model, classes, vocab, counts)
    print
    print "Accuracy with PCA Features"
    pca_rat = PCA(n_components=topic)
    pca_features = pca_rat.fit_transform(counts)
    min_acc, max_acc, avg_acc = KFoldCrossValidation(pca_features, classes, 5)
    print
    print
    print

Rat Classification accuracy on raw counts
Max Accuracy:  1.0 
Min Accuracy:  0.984375 
Average Accuracy:  0.996875



Rat Classification with numTopics =  5
Accuracy with original features
Max Accuracy:  0.890625 
Min Accuracy:  0.828125 
Average Accuracy:  0.86875

Accuracy with PCA Features
Max Accuracy:  0.671875 
Min Accuracy:  0.625 
Average Accuracy:  0.640625



Rat Classification with numTopics =  15
Accuracy with original features
Max Accuracy:  1.0 
Min Accuracy:  0.984375 
Average Accuracy:  0.996875

Accuracy with PCA Features
Max Accuracy:  0.984375 
Min Accuracy:  0.953125 
Average Accuracy:  0.975



Rat Classification with numTopics =  25
Accuracy with original features
Max Accuracy:  1.0 
Min Accuracy:  0.984375 
Average Accuracy:  0.99375

Accuracy with PCA Features
Max Accuracy:  1.0 
Min Accuracy:  0.984375 
Average Accuracy:  0.99375



Rat Classification with numTopics =  35
Accuracy with original features
Max Accuracy:  1.0 
Min Accuracy:  1.0 
Average Accuracy: 

# Neuron Dataset - 15, 25, 35 topics

In [13]:
neuron_topics_options = [5, 15, 25, 35]

In [14]:
print "Rat Classification accuracy on raw counts"
model, classes, vocab, counts = loadSavedModel(5, "neuron")
KFoldCrossValidation(counts, classes, 5)
print
print
print

for topic in neuron_topics_options:
    model, classes, vocab, counts = loadSavedModel(topic, "neuron")
    print "Neuron Classification with numTopics = ", topic
    print "Accuracy with original features"
    getClassificationAccuracy(model, classes, vocab, counts)
    print
    print "Accuracy with PCA Features"
    pca_neuron = PCA(n_components=topic)
    pca_features = pca_rat.fit_transform(counts)
    min_acc, max_acc, avg_acc = KFoldCrossValidation(pca_features, classes, 5)
    print
    print
    print

Rat Classification accuracy on raw counts
Max Accuracy:  0.97 
Min Accuracy:  0.91 
Average Accuracy:  0.934



Neuron Classification with numTopics =  5
Accuracy with original features
Max Accuracy:  0.84 
Min Accuracy:  0.72 
Average Accuracy:  0.76

Accuracy with PCA Features
Max Accuracy:  0.93 
Min Accuracy:  0.87 
Average Accuracy:  0.91



Neuron Classification with numTopics =  15
Accuracy with original features
Max Accuracy:  0.94 
Min Accuracy:  0.9 
Average Accuracy:  0.922

Accuracy with PCA Features
Max Accuracy:  0.94 
Min Accuracy:  0.87 
Average Accuracy:  0.904



Neuron Classification with numTopics =  25
Accuracy with original features
Max Accuracy:  0.93 
Min Accuracy:  0.9 
Average Accuracy:  0.916

Accuracy with PCA Features
Max Accuracy:  0.98 
Min Accuracy:  0.85 
Average Accuracy:  0.906



Neuron Classification with numTopics =  35
Accuracy with original features
Max Accuracy:  0.96 
Min Accuracy:  0.87 
Average Accuracy:  0.912

Accuracy with PCA Features
Max

In [15]:
def explore_relationships(numTopics, source):
    model, classes, vocab, counts = loadSavedModel(numTopics, source)
    # Get the top genes in each topic
    n_top_words = 25
    for i, topic_dist in enumerate(model.beta):
        topic_words = np.array(vocab)[np.argsort(topic_dist)][:-n_top_words:-1]
        print('Topic {}: {}'.format(i+1, ' '.join(topic_words)))
        print ""
    print "Covariance matrix"
    print model.sigma
    

In [16]:
explore_relationships(15, "neuron")

Topic 1: Cst3 Sparcl1 Apoe Slc1a2 Mt1 Atp1a2 Clu Dbi Cpe Rps29 Slc1a3 Prdx6 Sparc Ckb Mt2 Sepp1 Lars2 Rplp1 Aqp4 Actg1 Ptn Prdx1 Glul Itm2b

Topic 2: Ttr Usmg5 Cox7c Mdh1 Rps29 Dynll1 Gstp1 Ndufa4 Pcsk2 Slc25a4 Cox6c Atp5e Enpp2 Cox7a2 Atp5g1 Camk2n1 Snca Snhg11 Uqcrh Cycs Scg5 Ttc3 Atp5g3 Atp5j

Topic 3: Rps29 Npy Rplp1 Ftl1 Rps28 Rpl32 Rps3 Ndufa4 H3f3b Cox7c Akr1a1 Rpl18a Rpl35 Mdh1 Itm2b Atp6v1a Cox8a Tubb2a Fau Ddx5 Eef1a1 Rpl23 2010107E04Rik Rplp2

Topic 4: Slc25a4 Usmg5 Scg5 Stmn3 Mdh1 Cox6b1 Eif4a2 Cox8a Atpif1 Cox4i1 Mif Atp5b Cycs Uqcrq Atp5j2 Tpi1 Atp6v1a Fau Zwint Tecr Rpl4 Atp5f1 Oaz1-ps Ndufa13

Topic 5: Nrgn Snhg11 Rtn1 Ppp3ca Aplp1 Prkcb Prnp Camk2n1 Camk2b Nrxn1 Cpe Kif1b Itm2b Camk2a Celf2 Chn1 Lars2 Grin2b Rgs4 Gpm6b 2900097C17Rik Ttc3 Rtn4 Hpca

Topic 6: Ndufa4 Mdh1 Cox6c Sub1 Aldoa Cox7a2 Actg1 Cox7b Pcp4 Stmn2 Chn1 Cycs Syt1 Slc25a4 2010107E04Rik Atp5l Uqcrh Lars2 Tagln3 Atp5e Atp6v1d Ndufa5 Atp5c1 Uqcrq

Topic 7: Snca Scg5 Dynll1 Fkbp1a Calm3 Sub1 Itm2b Prnp Seri